-- ============================================================
-- Captura de reproducibilidad del esquema RBAC
-- ============================================================
-- El sistema de roles (empresa_usuarios, matriz_permisos_seed,
-- permiso_modulo_map, super_admins, fn_tiene_permiso,
-- fn_crear_empresa_usuario, is_super_admin) fue creado directo en
-- Postgres y nunca quedó versionado en supabase/migrations/. Esta
-- migración es un "no-op" contra la base actual (todo CREATE TABLE
-- IF NOT EXISTS / CREATE OR REPLACE), pero deja el esquema
-- reproducible si el entorno se recrea desde cero. Es prerrequisito
-- de la migración que agrega el rol 'cajero'.
-- ============================================================

CREATE TABLE IF NOT EXISTS super_admins (
  usuario_id  UUID PRIMARY KEY REFERENCES auth.users(id),
  email       TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS empresa_usuarios (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  empresa_id        UUID NOT NULL,
  rol               TEXT NOT NULL CHECK (rol = ANY (ARRAY['admin','contador','auxiliar','ventas'])),
  permisos_custom   JSONB,
  suspendido        BOOLEAN NOT NULL DEFAULT false,
  suspendido_at     TIMESTAMPTZ,
  suspendido_por    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  suspendido_razon  TEXT,
  creado_por        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (usuario_id, empresa_id)
);

CREATE INDEX IF NOT EXISTS idx_empresa_usuarios_usuario ON empresa_usuarios(usuario_id);
CREATE INDEX IF NOT EXISTS idx_empresa_usuarios_empresa ON empresa_usuarios(empresa_id);

CREATE TABLE IF NOT EXISTS matriz_permisos_seed (
  permiso    TEXT NOT NULL,
  rol        TEXT NOT NULL CHECK (rol = ANY (ARRAY['admin','contador','auxiliar','ventas'])),
  permitido  BOOLEAN NOT NULL,
  PRIMARY KEY (permiso, rol)
);

CREATE TABLE IF NOT EXISTS permiso_modulo_map (
  permiso  TEXT PRIMARY KEY,
  modulo   TEXT NOT NULL,
  tipo     TEXT NOT NULL CHECK (tipo = ANY (ARRAY['ver','editar']))
);

CREATE TABLE IF NOT EXISTS audit_log_accesos (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id           UUID,
  accion             TEXT NOT NULL,
  target_usuario_id  UUID,
  target_empresa_id  UUID,
  detalle            JSONB,
  razon              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE super_admins       ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresa_usuarios   ENABLE ROW LEVEL SECURITY;
ALTER TABLE matriz_permisos_seed ENABLE ROW LEVEL SECURITY;
ALTER TABLE permiso_modulo_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log_accesos  ENABLE ROW LEVEL SECURITY;

-- ── Funciones ────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION is_super_admin(p_usuario_id UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS(SELECT 1 FROM super_admins WHERE usuario_id = p_usuario_id);
$$;

CREATE OR REPLACE FUNCTION fn_validar_empresa_id_empresa_usuarios()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM empresas_persona_natural WHERE id = NEW.empresa_id
    UNION ALL
    SELECT 1 FROM empresas_juridicas WHERE id = NEW.empresa_id
  ) THEN
    RAISE EXCEPTION 'empresa_id % no existe en empresas_persona_natural ni empresas_juridicas', NEW.empresa_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_empresa_id_empresa_usuarios ON empresa_usuarios;
CREATE CONSTRAINT TRIGGER trg_validar_empresa_id_empresa_usuarios
  AFTER INSERT OR UPDATE OF empresa_id ON empresa_usuarios
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION fn_validar_empresa_id_empresa_usuarios();

CREATE OR REPLACE FUNCTION fn_tiene_permiso(p_usuario_id UUID, p_empresa_id UUID, p_permiso TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_empresa_usuario RECORD;
  v_empresa_suspendida BOOLEAN;
  v_es_super_admin BOOLEAN;
  v_modulo_map RECORD;
  v_permiso_matriz BOOLEAN;
BEGIN
  v_es_super_admin := is_super_admin(p_usuario_id);

  SELECT COALESCE(
    (SELECT suspendida FROM empresas_juridicas WHERE id = p_empresa_id),
    (SELECT suspendida FROM empresas_persona_natural WHERE id = p_empresa_id),
    false
  ) INTO v_empresa_suspendida;

  IF v_empresa_suspendida THEN
    IF v_es_super_admin THEN
      RETURN right(p_permiso, 4) = '_ver' OR p_permiso = 'dashboard_ver';
    END IF;
    RETURN false;
  END IF;

  IF v_es_super_admin THEN
    RETURN true;
  END IF;

  SELECT * INTO v_empresa_usuario FROM empresa_usuarios
    WHERE usuario_id = p_usuario_id AND empresa_id = p_empresa_id;
  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF v_empresa_usuario.suspendido THEN
    RETURN false;
  END IF;

  IF v_empresa_usuario.permisos_custom IS NOT NULL THEN
    SELECT * INTO v_modulo_map FROM permiso_modulo_map WHERE permiso = p_permiso;
    IF FOUND THEN
      IF (v_empresa_usuario.permisos_custom -> v_modulo_map.modulo) ? v_modulo_map.tipo THEN
        RETURN (v_empresa_usuario.permisos_custom -> v_modulo_map.modulo ->> v_modulo_map.tipo)::boolean;
      END IF;
    END IF;
  END IF;

  SELECT permitido INTO v_permiso_matriz FROM matriz_permisos_seed
    WHERE permiso = p_permiso AND rol = v_empresa_usuario.rol;
  RETURN COALESCE(v_permiso_matriz, false);
END;
$$;

CREATE OR REPLACE FUNCTION fn_crear_empresa_usuario(p_usuario_id UUID, p_empresa_id UUID, p_rol TEXT)
RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_actor UUID := auth.uid();
  v_id UUID;
BEGIN
  IF NOT is_super_admin(v_actor) AND NOT fn_tiene_permiso(v_actor, p_empresa_id, 'usuarios_gestionar') THEN
    RAISE EXCEPTION 'No tienes permiso para crear usuarios en esta empresa';
  END IF;
  IF p_rol = 'admin' AND NOT is_super_admin(v_actor) THEN
    RAISE EXCEPTION 'Solo super_admin puede asignar el rol admin';
  END IF;

  INSERT INTO empresa_usuarios (usuario_id, empresa_id, rol, creado_por)
    VALUES (p_usuario_id, p_empresa_id, p_rol, v_actor)
    RETURNING id INTO v_id;

  INSERT INTO audit_log_accesos (actor_id, accion, target_usuario_id, target_empresa_id, detalle)
    VALUES (v_actor, 'crear_usuario', p_usuario_id, p_empresa_id, jsonb_build_object('rol', p_rol));

  RETURN v_id;
END;
$$;

-- ── RLS ──────────────────────────────────────────────────────
DROP POLICY IF EXISTS "select_solo_super_admin" ON super_admins;
CREATE POLICY "select_solo_super_admin" ON super_admins
  FOR SELECT USING (is_super_admin(auth.uid()));

DROP POLICY IF EXISTS "select_propio_o_admin" ON empresa_usuarios;
CREATE POLICY "select_propio_o_admin" ON empresa_usuarios
  FOR SELECT USING (
    usuario_id = auth.uid()
    OR is_super_admin(auth.uid())
    OR fn_tiene_permiso(auth.uid(), empresa_id, 'usuarios_ver')
  );

DROP POLICY IF EXISTS "select_autenticados" ON matriz_permisos_seed;
CREATE POLICY "select_autenticados" ON matriz_permisos_seed
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "select_autenticados" ON permiso_modulo_map;
CREATE POLICY "select_autenticados" ON permiso_modulo_map
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "select_super_admin_o_admin_empresa" ON audit_log_accesos;
CREATE POLICY "select_super_admin_o_admin_empresa" ON audit_log_accesos
  FOR SELECT USING (
    is_super_admin(auth.uid())
    OR (target_empresa_id IS NOT NULL AND fn_tiene_permiso(auth.uid(), target_empresa_id, 'usuarios_ver'))
  );
